volumes:
  db:

services:
  mailonapi:
    image: mailonapi:latest
    container_name: mailonapi
    restart: always
    ports:
      - "6780:8080"

  mailonapidb:
    image: mysql:latest
    container_name: mailonapidb-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: putyourshere
    ports:
      - "3308:3306"
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql